sudo: required

language: generic

services:
  - docker

branches:
  only:
  - main

bofore_install:
  - echo "Start creating an image with dockerfile"
  - docker build -t react-test -f Dockerfile.dev ./

script:
  - docker run -e CI-true react-test npm run test -- --coverage

after_success:
  - echo "Test success"

after_failure:
  - echo "Test fail.."