sudo: required

language: generic

services:
  - docker

branches:
  only:
  - main

bofore_install:
  - echo "Start creating an image with dockerfile"
  - docker build -t react-test ./

script:
  - docker run -e CI=true react-test npm run test -- --coverage

after_success:
  - echo "Test success"

after_failure:
  - echo "Test fail.."

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-app-deploy-test"
  env: "Reactappdeploytest-env"
  bucket_name: "elasticbeanstalk-us-east-1-276223326741"
  bucket_path: "docker-app-deploy-test"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
